- name: Install and run nginx
  hosts: ngnix
  become: yes
  tasks: 
  - name: Install nginx
    ansible.bulitin.yum:
      name: nginx
      state: installed  
  - name: start nginx
    ansible.bulitin.service:
      name: nginx
      state: started      
